# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _oemaestro
else:
    import _oemaestro

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _oemaestro.delete_SwigPyIterator

    def value(self):
        return _oemaestro.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _oemaestro.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _oemaestro.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _oemaestro.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _oemaestro.SwigPyIterator_equal(self, x)

    def copy(self):
        return _oemaestro.SwigPyIterator_copy(self)

    def next(self):
        return _oemaestro.SwigPyIterator_next(self)

    def __next__(self):
        return _oemaestro.SwigPyIterator___next__(self)

    def previous(self):
        return _oemaestro.SwigPyIterator_previous(self)

    def advance(self, n):
        return _oemaestro.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _oemaestro.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _oemaestro.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _oemaestro.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _oemaestro.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _oemaestro.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _oemaestro.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _oemaestro:
_oemaestro.SwigPyIterator_swigregister(SwigPyIterator)
class StringStringMap(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _oemaestro.StringStringMap_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _oemaestro.StringStringMap___nonzero__(self)

    def __bool__(self):
        return _oemaestro.StringStringMap___bool__(self)

    def __len__(self):
        return _oemaestro.StringStringMap___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _oemaestro.StringStringMap___getitem__(self, key)

    def __delitem__(self, key):
        return _oemaestro.StringStringMap___delitem__(self, key)

    def has_key(self, key):
        return _oemaestro.StringStringMap_has_key(self, key)

    def keys(self):
        return _oemaestro.StringStringMap_keys(self)

    def values(self):
        return _oemaestro.StringStringMap_values(self)

    def items(self):
        return _oemaestro.StringStringMap_items(self)

    def __contains__(self, key):
        return _oemaestro.StringStringMap___contains__(self, key)

    def key_iterator(self):
        return _oemaestro.StringStringMap_key_iterator(self)

    def value_iterator(self):
        return _oemaestro.StringStringMap_value_iterator(self)

    def __setitem__(self, *args):
        return _oemaestro.StringStringMap___setitem__(self, *args)

    def asdict(self):
        return _oemaestro.StringStringMap_asdict(self)

    def __init__(self, *args):
        _oemaestro.StringStringMap_swiginit(self, _oemaestro.new_StringStringMap(*args))

    def empty(self):
        return _oemaestro.StringStringMap_empty(self)

    def size(self):
        return _oemaestro.StringStringMap_size(self)

    def swap(self, v):
        return _oemaestro.StringStringMap_swap(self, v)

    def begin(self):
        return _oemaestro.StringStringMap_begin(self)

    def end(self):
        return _oemaestro.StringStringMap_end(self)

    def rbegin(self):
        return _oemaestro.StringStringMap_rbegin(self)

    def rend(self):
        return _oemaestro.StringStringMap_rend(self)

    def clear(self):
        return _oemaestro.StringStringMap_clear(self)

    def get_allocator(self):
        return _oemaestro.StringStringMap_get_allocator(self)

    def count(self, x):
        return _oemaestro.StringStringMap_count(self, x)

    def erase(self, *args):
        return _oemaestro.StringStringMap_erase(self, *args)

    def find(self, x):
        return _oemaestro.StringStringMap_find(self, x)

    def lower_bound(self, x):
        return _oemaestro.StringStringMap_lower_bound(self, x)

    def upper_bound(self, x):
        return _oemaestro.StringStringMap_upper_bound(self, x)
    __swig_destroy__ = _oemaestro.delete_StringStringMap

# Register StringStringMap in _oemaestro:
_oemaestro.StringStringMap_swigregister(StringStringMap)
class MaestroAtomVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _oemaestro.MaestroAtomVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _oemaestro.MaestroAtomVector___nonzero__(self)

    def __bool__(self):
        return _oemaestro.MaestroAtomVector___bool__(self)

    def __len__(self):
        return _oemaestro.MaestroAtomVector___len__(self)

    def __getslice__(self, i, j):
        return _oemaestro.MaestroAtomVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _oemaestro.MaestroAtomVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _oemaestro.MaestroAtomVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _oemaestro.MaestroAtomVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _oemaestro.MaestroAtomVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _oemaestro.MaestroAtomVector___setitem__(self, *args)

    def pop(self):
        return _oemaestro.MaestroAtomVector_pop(self)

    def append(self, x):
        return _oemaestro.MaestroAtomVector_append(self, x)

    def empty(self):
        return _oemaestro.MaestroAtomVector_empty(self)

    def size(self):
        return _oemaestro.MaestroAtomVector_size(self)

    def swap(self, v):
        return _oemaestro.MaestroAtomVector_swap(self, v)

    def begin(self):
        return _oemaestro.MaestroAtomVector_begin(self)

    def end(self):
        return _oemaestro.MaestroAtomVector_end(self)

    def rbegin(self):
        return _oemaestro.MaestroAtomVector_rbegin(self)

    def rend(self):
        return _oemaestro.MaestroAtomVector_rend(self)

    def clear(self):
        return _oemaestro.MaestroAtomVector_clear(self)

    def get_allocator(self):
        return _oemaestro.MaestroAtomVector_get_allocator(self)

    def pop_back(self):
        return _oemaestro.MaestroAtomVector_pop_back(self)

    def erase(self, *args):
        return _oemaestro.MaestroAtomVector_erase(self, *args)

    def __init__(self, *args):
        _oemaestro.MaestroAtomVector_swiginit(self, _oemaestro.new_MaestroAtomVector(*args))

    def push_back(self, x):
        return _oemaestro.MaestroAtomVector_push_back(self, x)

    def front(self):
        return _oemaestro.MaestroAtomVector_front(self)

    def back(self):
        return _oemaestro.MaestroAtomVector_back(self)

    def assign(self, n, x):
        return _oemaestro.MaestroAtomVector_assign(self, n, x)

    def resize(self, *args):
        return _oemaestro.MaestroAtomVector_resize(self, *args)

    def insert(self, *args):
        return _oemaestro.MaestroAtomVector_insert(self, *args)

    def reserve(self, n):
        return _oemaestro.MaestroAtomVector_reserve(self, n)

    def capacity(self):
        return _oemaestro.MaestroAtomVector_capacity(self)
    __swig_destroy__ = _oemaestro.delete_MaestroAtomVector

# Register MaestroAtomVector in _oemaestro:
_oemaestro.MaestroAtomVector_swigregister(MaestroAtomVector)
class MaestroBondVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _oemaestro.MaestroBondVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _oemaestro.MaestroBondVector___nonzero__(self)

    def __bool__(self):
        return _oemaestro.MaestroBondVector___bool__(self)

    def __len__(self):
        return _oemaestro.MaestroBondVector___len__(self)

    def __getslice__(self, i, j):
        return _oemaestro.MaestroBondVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _oemaestro.MaestroBondVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _oemaestro.MaestroBondVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _oemaestro.MaestroBondVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _oemaestro.MaestroBondVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _oemaestro.MaestroBondVector___setitem__(self, *args)

    def pop(self):
        return _oemaestro.MaestroBondVector_pop(self)

    def append(self, x):
        return _oemaestro.MaestroBondVector_append(self, x)

    def empty(self):
        return _oemaestro.MaestroBondVector_empty(self)

    def size(self):
        return _oemaestro.MaestroBondVector_size(self)

    def swap(self, v):
        return _oemaestro.MaestroBondVector_swap(self, v)

    def begin(self):
        return _oemaestro.MaestroBondVector_begin(self)

    def end(self):
        return _oemaestro.MaestroBondVector_end(self)

    def rbegin(self):
        return _oemaestro.MaestroBondVector_rbegin(self)

    def rend(self):
        return _oemaestro.MaestroBondVector_rend(self)

    def clear(self):
        return _oemaestro.MaestroBondVector_clear(self)

    def get_allocator(self):
        return _oemaestro.MaestroBondVector_get_allocator(self)

    def pop_back(self):
        return _oemaestro.MaestroBondVector_pop_back(self)

    def erase(self, *args):
        return _oemaestro.MaestroBondVector_erase(self, *args)

    def __init__(self, *args):
        _oemaestro.MaestroBondVector_swiginit(self, _oemaestro.new_MaestroBondVector(*args))

    def push_back(self, x):
        return _oemaestro.MaestroBondVector_push_back(self, x)

    def front(self):
        return _oemaestro.MaestroBondVector_front(self)

    def back(self):
        return _oemaestro.MaestroBondVector_back(self)

    def assign(self, n, x):
        return _oemaestro.MaestroBondVector_assign(self, n, x)

    def resize(self, *args):
        return _oemaestro.MaestroBondVector_resize(self, *args)

    def insert(self, *args):
        return _oemaestro.MaestroBondVector_insert(self, *args)

    def reserve(self, n):
        return _oemaestro.MaestroBondVector_reserve(self, n)

    def capacity(self):
        return _oemaestro.MaestroBondVector_capacity(self)
    __swig_destroy__ = _oemaestro.delete_MaestroBondVector

# Register MaestroBondVector in _oemaestro:
_oemaestro.MaestroBondVector_swigregister(MaestroBondVector)
TAG_NONE = _oemaestro.TAG_NONE
TAG_TYPE = _oemaestro.TAG_TYPE
TAG_OWNER = _oemaestro.TAG_OWNER
TAG_NAME = _oemaestro.TAG_NAME
TAG_ALL = _oemaestro.TAG_ALL
PERCEPTION_NONE = _oemaestro.PERCEPTION_NONE
PERCEPTION_CONNECTIVITY = _oemaestro.PERCEPTION_CONNECTIVITY
PERCEPTION_RINGS = _oemaestro.PERCEPTION_RINGS
PERCEPTION_BOND_ORDERS = _oemaestro.PERCEPTION_BOND_ORDERS
PERCEPTION_IMPLICIT_HYDROGENS = _oemaestro.PERCEPTION_IMPLICIT_HYDROGENS
PERCEPTION_FORMAL_CHARGES = _oemaestro.PERCEPTION_FORMAL_CHARGES
PERCEPTION_ALL = _oemaestro.PERCEPTION_ALL
PERCEPTION_DEFAULT = _oemaestro.PERCEPTION_DEFAULT
class OEMaestroReaderConfig(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _oemaestro.OEMaestroReaderConfig_swiginit(self, _oemaestro.new_OEMaestroReaderConfig(*args))

    def SetTags(self, tags):
        return _oemaestro.OEMaestroReaderConfig_SetTags(self, tags)

    def GetTags(self):
        return _oemaestro.OEMaestroReaderConfig_GetTags(self)

    def SetPerception(self, perception):
        return _oemaestro.OEMaestroReaderConfig_SetPerception(self, perception)

    def GetPerception(self):
        return _oemaestro.OEMaestroReaderConfig_GetPerception(self)

    def SetNumThreads(self, num_threads):
        return _oemaestro.OEMaestroReaderConfig_SetNumThreads(self, num_threads)

    def GetNumThreads(self):
        return _oemaestro.OEMaestroReaderConfig_GetNumThreads(self)
    __swig_destroy__ = _oemaestro.delete_OEMaestroReaderConfig

# Register OEMaestroReaderConfig in _oemaestro:
_oemaestro.OEMaestroReaderConfig_swigregister(OEMaestroReaderConfig)
WRITE_CREATE = _oemaestro.WRITE_CREATE
WRITE_APPEND = _oemaestro.WRITE_APPEND
class OEMaestroWriterConfig(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _oemaestro.OEMaestroWriterConfig_swiginit(self, _oemaestro.new_OEMaestroWriterConfig(*args))

    def SetTags(self, tags):
        return _oemaestro.OEMaestroWriterConfig_SetTags(self, tags)

    def GetTags(self):
        return _oemaestro.OEMaestroWriterConfig_GetTags(self)

    def SetMode(self, mode):
        return _oemaestro.OEMaestroWriterConfig_SetMode(self, mode)

    def GetMode(self):
        return _oemaestro.OEMaestroWriterConfig_GetMode(self)

    def SetDefaultOwner(self, owner):
        return _oemaestro.OEMaestroWriterConfig_SetDefaultOwner(self, owner)

    def GetDefaultOwner(self):
        return _oemaestro.OEMaestroWriterConfig_GetDefaultOwner(self)
    __swig_destroy__ = _oemaestro.delete_OEMaestroWriterConfig

# Register OEMaestroWriterConfig in _oemaestro:
_oemaestro.OEMaestroWriterConfig_swigregister(OEMaestroWriterConfig)
class OEMaestroTagConverter(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _oemaestro.OEMaestroTagConverter_swiginit(self, _oemaestro.new_OEMaestroTagConverter(*args))

    def ToFormatted(self, maestro_key):
        return _oemaestro.OEMaestroTagConverter_ToFormatted(self, maestro_key)

    def ToMaestroTag(self, *args):
        return _oemaestro.OEMaestroTagConverter_ToMaestroTag(self, *args)

    @staticmethod
    def IsFullMaestroKey(key):
        return _oemaestro.OEMaestroTagConverter_IsFullMaestroKey(key)

    def GetTags(self):
        return _oemaestro.OEMaestroTagConverter_GetTags(self)

    def SetTags(self, tags):
        return _oemaestro.OEMaestroTagConverter_SetTags(self, tags)

    def GetDefaultOwner(self):
        return _oemaestro.OEMaestroTagConverter_GetDefaultOwner(self)

    def SetDefaultOwner(self, owner):
        return _oemaestro.OEMaestroTagConverter_SetDefaultOwner(self, owner)
    __swig_destroy__ = _oemaestro.delete_OEMaestroTagConverter

# Register OEMaestroTagConverter in _oemaestro:
_oemaestro.OEMaestroTagConverter_swigregister(OEMaestroTagConverter)
class OEMaestroError(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, message):
        _oemaestro.OEMaestroError_swiginit(self, _oemaestro.new_OEMaestroError(message))
    __swig_destroy__ = _oemaestro.delete_OEMaestroError

# Register OEMaestroError in _oemaestro:
_oemaestro.OEMaestroError_swigregister(OEMaestroError)
class MaestroParseError(OEMaestroError):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, message):
        _oemaestro.MaestroParseError_swiginit(self, _oemaestro.new_MaestroParseError(message))
    __swig_destroy__ = _oemaestro.delete_MaestroParseError

# Register MaestroParseError in _oemaestro:
_oemaestro.MaestroParseError_swigregister(MaestroParseError)
class MaestroConvertError(OEMaestroError):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, message):
        _oemaestro.MaestroConvertError_swiginit(self, _oemaestro.new_MaestroConvertError(message))
    __swig_destroy__ = _oemaestro.delete_MaestroConvertError

# Register MaestroConvertError in _oemaestro:
_oemaestro.MaestroConvertError_swigregister(MaestroConvertError)
class MaestroAtom(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    atomic_number = property(_oemaestro.MaestroAtom_atomic_number_get, _oemaestro.MaestroAtom_atomic_number_set)
    x = property(_oemaestro.MaestroAtom_x_get, _oemaestro.MaestroAtom_x_set)
    y = property(_oemaestro.MaestroAtom_y_get, _oemaestro.MaestroAtom_y_set)
    z = property(_oemaestro.MaestroAtom_z_get, _oemaestro.MaestroAtom_z_set)
    formal_charge = property(_oemaestro.MaestroAtom_formal_charge_get, _oemaestro.MaestroAtom_formal_charge_set)
    atom_name = property(_oemaestro.MaestroAtom_atom_name_get, _oemaestro.MaestroAtom_atom_name_set)
    residue_name = property(_oemaestro.MaestroAtom_residue_name_get, _oemaestro.MaestroAtom_residue_name_set)
    residue_number = property(_oemaestro.MaestroAtom_residue_number_get, _oemaestro.MaestroAtom_residue_number_set)
    chain_id = property(_oemaestro.MaestroAtom_chain_id_get, _oemaestro.MaestroAtom_chain_id_set)
    insert_code = property(_oemaestro.MaestroAtom_insert_code_get, _oemaestro.MaestroAtom_insert_code_set)
    bfactor = property(_oemaestro.MaestroAtom_bfactor_get, _oemaestro.MaestroAtom_bfactor_set)
    occupancy = property(_oemaestro.MaestroAtom_occupancy_get, _oemaestro.MaestroAtom_occupancy_set)
    is_ligand_atom = property(_oemaestro.MaestroAtom_is_ligand_atom_get, _oemaestro.MaestroAtom_is_ligand_atom_set)
    properties = property(_oemaestro.MaestroAtom_properties_get, _oemaestro.MaestroAtom_properties_set)

    def __repr__(self):
        return f"MaestroAtom(Z={self.atomic_number}, name='{self.atom_name}')"


    def __init__(self):
        _oemaestro.MaestroAtom_swiginit(self, _oemaestro.new_MaestroAtom())
    __swig_destroy__ = _oemaestro.delete_MaestroAtom

# Register MaestroAtom in _oemaestro:
_oemaestro.MaestroAtom_swigregister(MaestroAtom)
class MaestroBond(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    atom1_index = property(_oemaestro.MaestroBond_atom1_index_get, _oemaestro.MaestroBond_atom1_index_set)
    atom2_index = property(_oemaestro.MaestroBond_atom2_index_get, _oemaestro.MaestroBond_atom2_index_set)
    order = property(_oemaestro.MaestroBond_order_get, _oemaestro.MaestroBond_order_set)

    def __init__(self):
        _oemaestro.MaestroBond_swiginit(self, _oemaestro.new_MaestroBond())
    __swig_destroy__ = _oemaestro.delete_MaestroBond

# Register MaestroBond in _oemaestro:
_oemaestro.MaestroBond_swigregister(MaestroBond)
class MaestroMol(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    title = property(_oemaestro.MaestroMol_title_get, _oemaestro.MaestroMol_title_set)
    atoms = property(_oemaestro.MaestroMol_atoms_get, _oemaestro.MaestroMol_atoms_set)
    bonds = property(_oemaestro.MaestroMol_bonds_get, _oemaestro.MaestroMol_bonds_set)
    ct_properties = property(_oemaestro.MaestroMol_ct_properties_get, _oemaestro.MaestroMol_ct_properties_set)

    def NumAtoms(self):
        return _oemaestro.MaestroMol_NumAtoms(self)

    def NumBonds(self):
        return _oemaestro.MaestroMol_NumBonds(self)

    def ToString(self):
        return _oemaestro.MaestroMol_ToString(self)

    def __repr__(self):
        return self.ToString()


    def __init__(self):
        _oemaestro.MaestroMol_swiginit(self, _oemaestro.new_MaestroMol())
    __swig_destroy__ = _oemaestro.delete_MaestroMol

# Register MaestroMol in _oemaestro:
_oemaestro.MaestroMol_swigregister(MaestroMol)
class MaestroReader(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def Read(self, mol):
        return _oemaestro.MaestroReader_Read(self, mol)
    __swig_destroy__ = _oemaestro.delete_MaestroReader

    def __init__(self, *args):
        _oemaestro.MaestroReader_swiginit(self, _oemaestro.new_MaestroReader(*args))

# Register MaestroReader in _oemaestro:
_oemaestro.MaestroReader_swigregister(MaestroReader)
class MolConverter(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _oemaestro.MolConverter_swiginit(self, _oemaestro.new_MolConverter(*args))

    def Convert(self, *args):
        return _oemaestro.MolConverter_Convert(self, *args)

    def SetTagFormat(self, tags):
        return _oemaestro.MolConverter_SetTagFormat(self, tags)

    def GetTagFormat(self):
        return _oemaestro.MolConverter_GetTagFormat(self)

    def SetPerception(self, perception):
        return _oemaestro.MolConverter_SetPerception(self, perception)

    def GetPerception(self):
        return _oemaestro.MolConverter_GetPerception(self)
    __swig_destroy__ = _oemaestro.delete_MolConverter

# Register MolConverter in _oemaestro:
_oemaestro.MolConverter_swigregister(MolConverter)
class OEMaestroReader(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def Read(self, mol):
        return _oemaestro.OEMaestroReader_Read(self, mol)

    def GetPerception(self):
        return _oemaestro.OEMaestroReader_GetPerception(self)

    def GetTagFormat(self):
        return _oemaestro.OEMaestroReader_GetTagFormat(self)

    def GetConfig(self):
        return _oemaestro.OEMaestroReader_GetConfig(self)
    __swig_destroy__ = _oemaestro.delete_OEMaestroReader

    def __init__(self, *args):
        _oemaestro.OEMaestroReader_swiginit(self, _oemaestro.new_OEMaestroReader(*args))

    def __repr__(self):
        config = self.GetConfig()
        return f"OEMaestroReader(tags={config.GetTags()}, perception={config.GetPerception()})"


# Register OEMaestroReader in _oemaestro:
_oemaestro.OEMaestroReader_swigregister(OEMaestroReader)

def OEReadMaestro(*args):
    return _oemaestro.OEReadMaestro(*args)
class OEMaestroDesignUnitReader(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def Read(self, du):
        return _oemaestro.OEMaestroDesignUnitReader_Read(self, du)

    def SetLigandPredicate(self, pred):
        return _oemaestro.OEMaestroDesignUnitReader_SetLigandPredicate(self, pred)

    def SetSolventPredicate(self, pred):
        return _oemaestro.OEMaestroDesignUnitReader_SetSolventPredicate(self, pred)

    def SetCofactorPredicate(self, pred):
        return _oemaestro.OEMaestroDesignUnitReader_SetCofactorPredicate(self, pred)

    def GetPerception(self):
        return _oemaestro.OEMaestroDesignUnitReader_GetPerception(self)

    def GetTagFormat(self):
        return _oemaestro.OEMaestroDesignUnitReader_GetTagFormat(self)

    def GetConfig(self):
        return _oemaestro.OEMaestroDesignUnitReader_GetConfig(self)
    __swig_destroy__ = _oemaestro.delete_OEMaestroDesignUnitReader

    def __init__(self, *args):
        _oemaestro.OEMaestroDesignUnitReader_swiginit(self, _oemaestro.new_OEMaestroDesignUnitReader(*args))

    def __repr__(self):
        config = self.GetConfig()
        return f"OEMaestroDesignUnitReader(tags={config.GetTags()}, perception={config.GetPerception()})"


# Register OEMaestroDesignUnitReader in _oemaestro:
_oemaestro.OEMaestroDesignUnitReader_swigregister(OEMaestroDesignUnitReader)

def OEReadMaestroDesignUnit(*args):
    return _oemaestro.OEReadMaestroDesignUnit(*args)
class MaestroWriter(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def Write(self, mol):
        return _oemaestro.MaestroWriter_Write(self, mol)

    def Close(self):
        return _oemaestro.MaestroWriter_Close(self)
    __swig_destroy__ = _oemaestro.delete_MaestroWriter

    def __init__(self, *args):
        _oemaestro.MaestroWriter_swiginit(self, _oemaestro.new_MaestroWriter(*args))

# Register MaestroWriter in _oemaestro:
_oemaestro.MaestroWriter_swigregister(MaestroWriter)
class OEMaestroWriter(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def Write(self, mol):
        return _oemaestro.OEMaestroWriter_Write(self, mol)

    def Close(self):
        return _oemaestro.OEMaestroWriter_Close(self)
    __swig_destroy__ = _oemaestro.delete_OEMaestroWriter

    def __init__(self, *args):
        _oemaestro.OEMaestroWriter_swiginit(self, _oemaestro.new_OEMaestroWriter(*args))

    def __repr__(self):
        return "OEMaestroWriter()"


# Register OEMaestroWriter in _oemaestro:
_oemaestro.OEMaestroWriter_swigregister(OEMaestroWriter)

def OEWriteMaestro(*args):
    return _oemaestro.OEWriteMaestro(*args)

