[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "oemaestro"
version = "0.7.4"
description = "Native Maestro format parser for OpenEye Toolkits"
requires-python = ">=3.10"
dependencies = ["openeye-toolkits>=2025.2", "rich-click>=1.7"]

[project.scripts]
oemaestro = "oemaestro.cli:main"

[tool.setuptools]
packages = ["oemaestro"]
